### ISSUE TITLE
"ExtraResources" support

### ISSUE THREAD

**Issue by matheussige** [unindented/electron-installer-debian#127]
I have an Electron application that, when started, initializes a .NET Core API locally. On other platforms, I can just `cd /resources && ./apifile` and it will start.

However, on Linux, this gives me a permission error, since the file is installed at /usr/lib/resources and therefore only accessible by root user.

I think there should be a way to indicate an extraResources option, indicating a folder to copy to a defined location (/.config/appname maybe?) so this kind of setup can work.

Is there another way to do this in the meantime? I tried making a postinstall script, but cannot move the folder without root either.

**Comment by fcastilloec** [comment]
What OS version are you using? I don't think this is an issue with `electron-installer-debian`. For the next part, I'm assuming you're not very familiar with Linux and specifically Debian.
Your executable, even if it's in `/usr/lib/resources`, should have permissions that allow anybody to start the file. Also, you should have a link under `/usr/bin/` pointing to `/usr/lib/resources` so you can start the app from anywhere. `/usr/bin/` it's usually in your PATH by default.
Regarding the `postinstall` script, that script is run as `root` so you can do anything you want there. You should read the links under [README#options.scripts](https://github.com/unindented/electron-installer-debian#optionsscripts)

If you're using `options.bin`, make sure that is pointing to an executable, make sure the permission of the file is correct.

**Comment by matheussige** [comment]
Sorry for the lack of details earlier. I am using ElementaryOS 0.4.1, which is based on Ubuntu 16.04. You're right, I'm not very familiar with Linux.

My folder structure (after installed) is this:

```
/usr
   /bin
      my-app (links to /lib/my-app, works correctly)
   /lib
       /my-app
           /resources
               app.asar
               /dotnet-api
                   dotnet-api (executable)
```
When I start my app with the .desktop file, it tries to run:
`cd dotnet-api && ./dotnet-api`

And then it fails, with the following error: `/bin/sh: 1: ./dotnet-api: Permission denied`. It works when running via Terminal (sudo).

When running electron-installer-debian with the following postinst script:
```
#!/bin/bash
mv /dotnet-api ~/.config/my-app
```
The package doesn't get generated and gives the error: `dpkg-deb: error: maintainer script 'postinst' has bad permissions 664 (must be >=0555 and <=0775)`

**Comment by matheussige** [comment]
Okay, I managed to solve this. It was not an issue with electron-installer-debian indeed.

- Solving the `'postinst' has bad permissions 664` error:

   - My postinst script file had bad permissions, it had nothing to do with the packaging process. I just changed its permissions to 755 instead of 664 and it was solved.

- I created a postinst script that changed the permissions for the API folder, like this:
```
#!/bin/bash
 sudo chmod -R 755 /usr/lib/sige-lite/resources/self-hosted-api
 exit 0
```

Then, my electron app was able to start the API just fine.
