### ISSUE TITLE
Generated symlink uses a wrong app name

### ISSUE THREAD

**Issue by tleunen** [unindented/electron-installer-debian#128]
**What version of `electron-installer-debian` are you using?**
electron-installer-debian@0.8.0 via electron-forge@5.1.0

**What version of `node` and `npm` are you using?**
Node 8.9.4
Npm 5.6.0

**What operating system are you using?**
Mac OS X High Sierra

**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**
Yes

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
```
electron-forge make --platform=linux
```
With this specific config:
```
electronInstallerDebian: {
    options: {
      genericName: 'Generic Name',
      categories: ['Network'],
      depends: ['libappindicator1', 'libnotify-bin', 'libasound2'],
      icon: '...',
      name: 'myapp-alpha',
      productName: 'MyApp-alpha',
    },
  },
```

**What did you expect to happen?**
The symlink in the .deb file should be valid

**What actually happened?**
The bin symlink is incorrect. Instead of going to `MyApp-alpha`, it goes to `myapp`.
```
❯ dpkg -c out/make/myapp-alpha_0.0.2_amd64.deb

-rwxr-xr-x tleunen/tleunen 83193520 2018-02-14 16:53 ./usr/lib/myapp-alpha/MyApp-alpha
lrwxr-xr-x tleunen/tleunen        0 2018-02-14 16:53 ./usr/bin/myapp-alpha -> ../lib/myapp-alpha/myapp
```

It seems that instead of using the `name` given in the `electronInstallerDebian` options, it uses the name from `package.json`. I'm explicitely set the name in order to be able to have different names for my alpha, beta and production app.

While building the binaries with the debug log, I can see the name seems correct though:
```
  electron-installer-debian [Desktop Entry]
  electron-installer-debian Name=MyApp-alpha
```

**Comment by tleunen** [comment]
My bad, while writing this issue, I was debugging the package at the same time and found out that I needed to provide the `bin` option, since `createBinary` uses that.

**Comment by fcastilloec** [comment]
Thanks for closing the issue, I was about to do the same. Always read the documentation before. Just in case, this is the relevant part https://github.com/unindented/electron-installer-debian#optionsbin
