### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by malept** [unindented/electron-installer-debian#136]
This issue should describe the criteria for releasing 1.0.0.

* [x] #120 
* [x] Drop callback support (#138)
* [ ] Drop Node 4 support (#145)

**Comment by malept** [comment]
* I'd like to finish #120 before we release.
* What do you think about dropping callback support? We can mention in the docs to use [`nodeify`](https://www.npmjs.com/package/nodeify) if callbacks are required.

> Drop Node 4

I don't want to drop Node 4 support until LTS support is dropped by Node itself at the end of April. That can be 2.0.0 (or whatever major version we end up on at that time).

**Comment by fcastilloec** [comment]
I like the idea of dropping callback support only. That will keep with semver definitions. Great idea.
Regarding #120. I like the idea of basing them on `electron-packager`, feel free to do it.
