### ISSUE TITLE
Dependence libgconf2-4 is a dummy package

### ISSUE THREAD

**Issue by asanzo** [unindented/electron-installer-debian#141]
Hi!

**What version of `electron-installer-debian` are you using?**
0.8.1
**What version of `node` and `npm` are you using?**
v6.11.3 and 3.10.10
**What operating system are you using?**
- To compile, Linux Mint 18.1 Mate 64bits
- To install the .deb, Huayra Linux 64 bits, based on Debian 8.3 and Mate 1.8.1

**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**
yes

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
In Linux Mint:
- `electron-installer-debian --src (my source) --dest (my dest) --arch amd64`

In Huayra: 
- I double click the .deb. I answer "Yes" to "Do you want to install this package". After starting the unpackaging process, it says  (In spanish) "Failure when installing".
- I then tried a `sudo dpkg -i` and says that it has unmet dependencies with "libgconf2-4", yet however **I do have installed the package libgconf-2-4** (note the extra hyphen). [Here](https://packages.debian.org/sid/libgconf2-4) it says that libgconf2-4 is a _dummy package_, so I think that every repository that has libgconf2-4 also has libgconf-2-4, but it's not the case in the other way (In Huayra repositories they only have the libgconf-2-4 package, which is exactly the same).

**What did you expect to happen?**
I expected to be able to install the .deb package in debian.

**What actually happened?**
It didn't.

Wouldn't it be better to have libgconf-2-4 as a dependency and not the dummy package?

Thanks!

**Comment by fcastilloec** [comment]
The majority of Debian-based OSs have the dummy package, which not only installs `libgconf` but has other dependencies as well. So by not using the dummy package, we will have to manually add all the other packages too.
I think it's more appropriate to file a bug on Huayra Linux requesting the dummy packages. You could also fork our repository and disable the lines that append the user dependencies to the default ones, so instead, they are replaced (see [`installer.js#L170`](https://github.com/unindented/electron-installer-debian/blob/v0.8.1/src/installer.js#L170)). We could add a setting instructing to either replace or append, but I personally don't think it's a good idea to have that.

**Comment by eeickmeyer** [comment]
This dummy package was removed from Ubuntu beginning in 19.04 and as such packages depending on the dummy package cannot install. I highly recommend changing the dependency on libgconf2.4 to "libgconf2-4 | libgconf-2-4".
