### ISSUE TITLE
Symbolic link not created in /usr/bin in Ubuntu 18.04

### ISSUE THREAD

**Issue by adred** [unindented/electron-installer-debian#143]
**What version of `electron-installer-debian` are you using?**
v0.8.1

**What version of `node` and `npm` are you using?**
8.11.1 and 6.0.1

**What operating system are you using?**
Ubuntu 18.04

**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**
yes

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
```
{
  "name": "test",
  "bin": "test",
  "userDataDir": "test",
  "productName": "test",
  "genericName": "test",
  "homepage": "https://test.com/",
  "icon": "res/dev/app.png",
  "section": "test",
  "categories": [
    "Network",
    "test"
  ],
  "mimeType": [
    "text/html",
    "text/xml",
    "application/xhtml_xml",
    "image/webp",
    "x-scheme-handler/http",
    "x-scheme-handler/https",
    "x-scheme-handler/ftp"
  ],
  "requires": [
    "GConf2",
    "libXScrnSaver",
    "lsb"
  ],
  "depends": [
    "gawk",
    "git",
    "gconf2",
    "gconf-service",
    "gvfs-bin",
    "libc6",
    "libcap2",
    "libgtk2.0-0",
    "libudev0 | libudev1",
    "libgcrypt11 | libgcrypt20",
    "libnotify4",
    "libnss3",
    "libxtst6",
    "libxss1",
    "python",
    "xdg-utils"
  ]
}

```
**What did you expect to happen?**
It should create a symbolic link in /usr/bin/myelectronapp

**What actually happened?**
No symbolic link created. But it was able to unpack the package in /usr/lib/myelectronapp

**Comment by malept** [comment]
Can you please rerun the command, but prepend `DEBUG=electron-installer-debian` beforehand?

**Comment by adred** [comment]
Okay will do. I'll be back.

**Comment by adred** [comment]
I get this error ```DEBUG=electron-installer-debian --src osiris-linux-x64/ --dest dist/ --arch amd64 --config res/dev/linuxPackaging.json
/bin/sh: 1: --src: not found```

**Comment by malept** [comment]
Run `DEBUG=electron-installer-debian electron-installer-debian --src test-linux-x64/ --dest dist/ --arch amd64 --config res/dev/linuxPackaging.json`

**Comment by adred** [comment]
```
Thu, 16 Aug 2018 05:39:06 GMT electron-installer-debian Symlinking binary from ../lib/Osiris/osiris to /tmp/electron-118716-11332-bgzt9h.ns10w/Osiris_0.1.0_amd64/usr/bin/Osiris
```

**Comment by adred** [comment]
Also, I'm confused why it's creating a symlink on build process. Shouldn't it be created when installing using `sudo dpkg -i app.deb`? Please enlighten me.

**Comment by malept** [comment]
Set the `bin` option to whatever the customized Electron binary is named.

> Also, I'm confused why it's creating a symlink on build process.

I'm not sure how it would know where the binary is. Also, adding a postinstall script by default would make it much more difficult to provide support for custom postinstall scripts.
