### ISSUE TITLE
wrong-file-owner-uid-or-gid error in package

### ISSUE THREAD

**Issue by PalmerAL** [unindented/electron-installer-debian#16]
I'm trying to build a Linux package using grunt-electron-installer-debian on OS X. The settings look like this:

```
        'electron-installer-debian': {
            options: {
                productName: "Min",
                genericName: "Web Browser",
                description: "A smarter, faster web browser",
                version: version,
                section: "web",
                homepage: "https://palmeral.github.io/min/",
                icon: "icons/icon256.png",
                categories: ["Network", "WebBrowser"],
                mimeType: ["x-scheme-handler/http", "x-scheme-handler/https", "text/html"]
            },
            linux32: {
                options: {
                    arch: 'i386'
                },
                src: 'dist/app/Min-linux-ia32',
                dest: 'dist/app/linux'
            },
            linux64: {
                options: {
                    arch: 'amd64'
                },
                src: 'dist/app/Min-linux-x64',
                dest: 'dist/app/linux'
            }
        }
```

The problem I'm running into is that I'm getting the `wrong-file-owner-uid-or-gid` error for every file in the package, which I guess means that the file permissions are incorrect. This also causes Ubuntu to refuse to install the package, claiming it is "bad quality". Are there any options I can change to fix this?

**Comment by unindented** [comment]
Do the original files have the right permissions? Are the permissions persisted when the files get copied, or are they reset?

**Comment by PalmerAL** [comment]
> Do the original files have the right permissions?

I think so, here are the permissions for one of the files:


<img width="256" alt="screen shot 2016-04-24" src="https://cloud.githubusercontent.com/assets/10314059/14769166/772600d0-0a18-11e6-8bc5-dfae577899a7.png">

>Are the permissions persisted when the files get copied, or are they reset?

If I copy them to another folder, the permissions stay the same.

**Comment by randoms** [comment]
I experience the same issue on Ubuntu 14.04.
Permissions after install
![screenshot from 2016-06-28 16 31 20](https://cloud.githubusercontent.com/assets/3120090/16408970/ce9fd15c-3d4d-11e6-9d63-d74bb1d9f5d4.png)
Before install
![screenshot from 2016-06-28 16 38 21](https://cloud.githubusercontent.com/assets/3120090/16409168/ca820d0a-3d4e-11e6-897c-c3c5dbc57184.png)

The Owner group of these files has changed to root. So jquey.js fails to load after install. I have to give other groups read permission to make it work.

**Comment by lurch** [comment]
> The Owner group of these files has changed to root

Isn't that expected behaviour, for files installed from a `.deb` package? Since you have to run `apt-get` or `dpkg` as root also.

**Comment by unindented** [comment]
Ah right, I wasn't understanding their issue. Yup, as @lurch says, the files in the `.deb` package are owned by root.
