### ISSUE TITLE
App not appearing in installed applications after .deb installation

### ISSUE THREAD

**Issue by jaypanares** [unindented/electron-installer-debian#19]
**What version of `electron-installer-debian` are you using?**
0.3.0

**What version of `node` and `npm` are you using?**
Node - v6.1.0
npm - 3.8.6

**What operating system are you using?**
Ubuntu 16.04 (VirtualBox VM)

**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**
Yes

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-debian.git
$ cd electron-installer-debian/example
$ DEBUG='electron-installer-debian' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
Followed readme, `npm install && npm run build`

**What did you expect to happen?**
App to appear in installed applications in Ubuntu

**What actually happened?**
.deb was built with no errors and app was installed without issues, but can't find the app in the installed applications menu

**Comment by unindented** [comment]
Thanks for reporting @jaypanares.

Are you sure the app installed without issues? Maybe Ubuntu errored silently...

Try executing the following from a command line:

```
sudo dpkg -i yourdebfile.deb
```

Did it complain about missing dependencies, like `libappindicator1`?

I tend to use `gdebi` to install `.deb` files, as it resolves dependencies automatically:

```
sudo apt-get install gdebi
sudo gdebi yourdebfile.deb
```

**Comment by jaypanares** [comment]
I got your example working using `gdebi` :)  Now, my issue is that the app I'm working on is not appearing in installed applications.  Are you doing anything special to add the icon in the installed apps?  I tried copying the `config.json` from your example and building the installer the same way as your `npm run build` but my app is not appearing in installed applications.  No errors are displayed.  Do I just depend on some packages and it should work?

**Comment by unindented** [comment]
The only thing the example app does is point to a PNG image to be used as icon: https://github.com/unindented/electron-installer-debian/blob/master/example/config.json#L3

Can you paste the contents of `/usr/share/applications/yourapp.desktop`? That's what Ubuntu uses to display your app in the launcher AFAIK.

**Comment by jaypanares** [comment]
Hmm.. The app appears in `/usr/share/applications` but when I run it `There was an error running the application`.  The built files from `electron-packager` work fine when I run them, but when I use `electron-installer-debian` I can't get the app to run.  Maybe that is what's wrong?

**Comment by jaypanares** [comment]
I tried creating an installer with Electron's quick start app:
`git clone https://github.com/electron/electron-quick-start`

I am also unable to run the app when I open it in `/usr/share/applications`

**Comment by unindented** [comment]
So only my example app works? That's weird... What differences have you noticed between your app and the example?

**Comment by jaypanares** [comment]
The only difference I noticed was that you app's structure is different from my app, but I think that that shouldn't be the case because there isn't any installer specific code in your app.

**Comment by randoms** [comment]
I experienced the same problem. Here is my desktop file

```
[Desktop Entry]
Name=path-drawer
Comment=A program to process ORB_SLAM2 map points and path
GenericName=path-drawer
Exec=path-drawer %U
Icon=path-drawer
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;
```

I think the Exec path is wrong. The right one is ```/usr/share/path-drawer/app```.

**Comment by randoms** [comment]
I found that a symbol link was created at ```/usr/bin```, but the link location was wrong.
current link address
```
../share/path-drawer/path-drawer
```
the right address should be
```
../share/path-drawer/app
```

**Comment by kniazkovqarea** [comment]
I have the same issue.
@jaypanares did you solve the problem?

**Comment by randoms** [comment]
change [src/installer.js L237](https://github.com/unindented/electron-installer-debian/blob/master/src/installer.js#L237) 

from 

```
var binSrc = path.join('../share', options.name, options.bin)
```

to

```
var binSrc = path.join('../share', options.name, "app")
```

**Comment by unindented** [comment]
@randoms instead of changing the source of the extension, what you should be doing is passing the `bin` option set to whatever you want:

```json
{
  "bin": "app"
}
```

**Comment by jaylenw** [comment]
Unfortunately, the bin parameter does not work for me when i added the correct string location for the application to excecute. :(

**Comment by DarthVader1108** [comment]
> Thanks for reporting @jaypanares.
> 
> Are you sure the app installed without issues? Maybe Ubuntu errored silently...
> 
> Try executing the following from a command line:
> 
> ```
> sudo dpkg -i yourdebfile.deb
> ```
> 
> Did it complain about missing dependencies, like `libappindicator1`?
> 
> I tend to use `gdebi` to install `.deb` files, as it resolves dependencies automatically:
> 
> ```
> sudo apt-get install gdebi
> sudo gdebi yourdebfile.deb
> ```

I tried that, but it keeps saying "file not found" even though I typed the right characters, the exact characters.
