### ISSUE TITLE
How to add more details about the package (screenshot, etc)

### ISSUE THREAD

**Issue by 0x00A** [unindented/electron-installer-debian#31]
**What version of `electron-installer-debian` are you using?**
0.3.0 (Electron 1.2.7)

**What version of `node` and `npm` are you using?**
6.3.0/3.10.3

**What operating system are you using?**
Elementary & Ubuntu

**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**
Yes

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**

I added all the options mentioned in the [`readme`](https://github.com/unindented/electron-installer-debian#options)
```
{
   src: '...',
   dest: '...',
   icon: 'path/to/icon'
}
```

**What did you expect to happen?**
On my Ubuntu machine, i see the icon just fine. But on ElementaryOS it's missing. It's a png file. Any clues? I'm also curious if you know how to add a screenshot here.

**What actually happened?**

![image](https://cloud.githubusercontent.com/assets/136109/16994330/e64c30ec-4e74-11e6-83e4-caed0fab9f69.png)

**Comment by unindented** [comment]
Not sure how ElementaryOS looks up the icon.

Regarding screenshots: http://askubuntu.com/questions/117130/how-to-include-a-screenshot-of-my-application-in-the-deb-ppa-to-show-it-in-softw
