### ISSUE TITLE
Maintainer attribute in control file isn't in the correct format

### ISSUE THREAD

**Issue by vidhu** [unindented/electron-installer-debian#39]
In the  /DEBIAN/control file, the maintainer attribute isn't in the correct format

Current it defaults to `package.author.name (package.author.email)`
The proper way is to have the email in angle brackets like this:
`package.author.name <package.author.email>`

This is according to https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Maintainer

**Comment by unindented** [comment]
Thanks for reporting. Can you make a pull request?
