### ISSUE TITLE
Use proper debian versioning for beta versions

### ISSUE THREAD

**Issue by dlech** [unindented/electron-installer-debian#44]
**What version of `electron-installer-debian` are you using?**
0.3.1
**What version of `node` and `npm` are you using?**
v6.1.0
3.8.6
**What operating system are you using?**
debian jessie

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
Built a debian package from an electron package. No special configuration.

    electron-installer-debian --src etcher-release/Etcher-linux-x64/ --dest etcher-release/debian/ --arch amd64

**What did you expect to happen?**

The debian package version should be `1.0.0~beta.15-1`

**What actually happened?**

The version was `1.0.0-beta.15-1`

**Comment by dlech** [comment]
According to debian versioning, `1.0.0-beta.15-1` > `1.0.0-1`. The correct thing to do for beta/rc/etc. is `1.0.0~beta.15-1`.

The [debian/watch docs](https://wiki.debian.org/debian/watch) provide the needed version mangling

    opts=uversionmangle=s/(\d)[_\.\-\+]?((RC|rc|pre|dev|beta|alpha)\d*)$/$1~$2/

This regex could be used by `electron-installer-debian` to automatically generate correct debian versions.

**Comment by unindented** [comment]
Good point. Do you mind creating a PR?
