### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by gch1p** [unindented/electron-installer-debian#52]
Hello. 

Why `git` and `python` were put in the list of package dependencies?

**Comment by unindented** [comment]
I think I just took whatever Atom was using in their control file: https://github.com/atom/atom/blob/7929e261a0d6e78ff4ca5196c8b385946e64dbd9/resources/linux/debian/control.in#L3

**Comment by unindented** [comment]
Feel free to open a PR with a fix.
