### ISSUE TITLE
App automatically installs in /usr/lib/ since 0.5.0

### ISSUE THREAD

**Issue by diegomarcov** [unindented/electron-installer-debian#56]
Since I upgraded to electron-installer-debian 0.5.0, I noticed that [this commit](https://github.com/unindented/electron-installer-debian/commit/9d5c524da37a2824afea176ed95a3feb3bdd7558) causes my app to install in /usr/lib. This is absolutely not desirable in our case, and I haven't found a way to at least configure this path.

I rolled back the dependency to 0.4.0 momentarily to fix this, but I wouldn't like to be stuck with that forever. Are there plans to make this path configurable (or am I missing this option somewhere)?

Thanks!

**Comment by unindented** [comment]
@dlech pointed out that Debian guidelines dictate that apps must live in `/usr/lib`, not `/usr/share`. Why is it not desirable in your case?

**Comment by diegomarcov** [comment]
Hi @unindented , sorry it took a bit to respond. In our case, we got reports from Linux users because their shortcuts stopped working. This is the way we actually found out about the change: our app used to be installed in /usr/share, and when we got the report we realized about the change in electron-installer-debian.

That was not a very serious problem, but discussing this further actually made us think that our app should be in /opt according to the guidelines, and not in /usr/share or /usr/lib, but I couldn't find a way at all to do this with electron-installer-debian. Maybe I can rephrase this issue or open a different one, but the real limitation is that we are not able to choose _where_ the app is installed using this tool.

Thanks, and sorry again for taking a couple of days to answer.

**Comment by dlech** [comment]
Since it is installed with a `.deb` package and it contains binary files, it belongs in `/usr/lib/`. If you install manually (e.g. from source), it would be correct to install in `/usr/local/lib/` or `/opt/`. It is actually against debian policy to install in `/opt/` from a `.deb` package.

**Comment by lurch** [comment]
This also caught us out in Etcher https://github.com/resin-io/etcher/pull/1290

Perhaps this change-of-path in 0.5.0 ought to be mentioned somewhere prominent in the README?

**Comment by unindented** [comment]
@lurch you are right. I'll try to add a note in the README.

**Comment by fcastilloec** [comment]
@malept could you also change the README to point out where the `.deb` is installed so we can close this issue?
