### ISSUE TITLE
Run update-desktop-database after [un]install

### ISSUE THREAD

**Issue by da2x** [unindented/electron-installer-debian#76]
I'm not as familiar with .deb packages as .rpm packages, but [the same post-install and post-uninstall scripts](https://github.com/unindented/electron-installer-redhat/pull/67) are needed for .deb.

I think you add a postinst and a postrm script with executable permissions to the control directory of the .deb, but I'm not entirely sure how it works.

**Comment by unindented** [comment]
You sure this is needed? On Ubuntu I get the icons to appear immediately after install...

**Comment by da2x** [comment]
I do believe so, yes. It could be that the Unity desktop more aggressively monitor the applications folder for changes, but I can't find any indication of this on the web.

**Comment by fcastilloec** [comment]
This has been fixed by PR #96
