### ISSUE TITLE
Unable to start application because /usr/lib/{app}/resources/app is only readable by root

### ISSUE THREAD

**Issue by bsod90** [unindented/electron-installer-debian#79]
**What version of `electron-installer-debian` are you using?**
0.5.1

**What version of `node` and `npm` are you using?**
node 6.9.1
npm 3.10.8

**What operating system are you using?**
ubuntu 16.04

**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**

**If not, paste here the output of the following commands:**

Compilation is successfull, but I can't start it:

http://d.pr/v/kvsw6H

```
$ git clone https://github.com/unindented/electron-installer-debian.git
$ cd electron-installer-debian/example
$ DEBUG='electron-installer-debian' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
I'm using ember-electron, which uses electron electron-forge, which uses electron-installer-debian.
I have built my project for Linux and tried to install it.

**What did you expect to happen?**

I expected the app to be installed and me being able to run it

**What actually happened?**

The app is installed, but unable to start due to a permissions issue.

Seems like electron is trying to load app from `/usr/lib/my_app/reousrces/app`, but after unpacking the .deb file, this location gets the permissions to be only readable by root:

![image](https://cloud.githubusercontent.com/assets/2292499/26563511/fd0df8ec-4487-11e7-8a0f-fc911e988cd9.png)

after I change permissions manually, the app starts fine:

![image](https://cloud.githubusercontent.com/assets/2292499/26563524/272c7590-4488-11e7-8154-ebe34c98e4ea.png)

![image](https://cloud.githubusercontent.com/assets/2292499/26563519/1b4cd616-4488-11e7-9306-815334731bd7.png)

**Comment by unindented** [comment]
I thought package files being owned by `root` was a requirement. I was getting lintian errors when I wasn't using `fakeroot`.

Can you try building the example app and reporting back? I've never had issues with this approach on Ubuntu, but I haven't tried Debian proper.

**Comment by unindented** [comment]
Ah, I see in the video you are also using Ubuntu... Can you try installing the package by double-clicking the file, instead of dpkg?

**Comment by bsod90** [comment]
Ha, this is weird.
It seems that it worked well when I installed it from UI. Even the tray indicator started to work (sort of). Now I'm wondering what's the difference :)

Well, seems there's a way to install it, it's good. However, I think that `dpkg -i` or `apt-get install` is still a default way of installing .deb packages for most of people, so it may be good to investigate why there's an inconsistency.

Thank you for your help!

**Comment by unindented** [comment]
It looks like`dpkg` on Ubuntu is not doing everything it needs to do, so it results in a broken installation.

If you installed through `apt-get install` I bet it'd work, cause that's what the UI is doing under the hood.

**Comment by bsod90** [comment]
We just had our first installations recently and people are reporting that .deb is broken even if they're going through GUI installer.
Simply doing `chmod a+rx /usr/lib/onebar/resources/app` fixes it.
So, for now I'm just re-opening the deb, changing the permission and packaging it back as a workaround. Then it works even through `dpkg`.
But for me it still looks like a bug, that should be fixed in electron-debian-installer. Perhaps I can fork it and use the custom version of it for our thing, but I'm just wondering what's the reason for it giving 700 permissions to `/usr/lib/<app>/resources/app` by default.

**Comment by unindented** [comment]
Have you tried the example app? It executes correctly, so I'd bet it's something having to do with your build process or environment.

**Comment by unindented** [comment]
Also, it's not my module that changes permissions, it's `fakeroot`. When you create a `.deb` file, `fakeroot` changes the owner of the files, because that's how you're supposed to package a `.deb` file. It doesn't change the executable flag though, so maybe compare your app with the example app, see if you find the problem.

**Comment by jochenkirstaetter** [comment]
Hi,
Somehow something is missing somewhere. Even an application like Ghost Desktop has this issue as reported here: https://github.com/TryGhost/Ghost-Desktop/issues/274

How it is done to package the .deb with correct permissions?

Thanks, Jochen

**Comment by unindented** [comment]
The Brave browser is using this library, and they haven't reported any issues: https://github.com/brave/browser-laptop/blob/07c6cd993a292edba2aad8710f8bf0d94467c81d/package.json#L194

Maybe check their build pipeline.
