### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by fcastilloec** [unindented/electron-installer-debian#86]
**What version of `electron-installer-debian` are you using?**
0.5.2
**What version of `node` and `npm` are you using?**
`node` 6.11.2
`npm` 3.10.10
**What operating system are you using?**
Ubuntu 16.04
**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**
Yes

There should be a way to append the `options.depends` list to the default list of dependencies listed in [electron-installer-debian/installer.js](https://github.com/unindented/electron-installer-debian/blob/master/src/installer.js) instead of overwriting it. In fact, the default behavior should be to always append, or unless specified by the user, overwrite.

PR #53 removed some dependencies, but are they all really needed to run the examples? The list was based on Atom, which might have higher requirements than the most basic of examples.

**Comment by malept** [comment]
I'm doing another round of investigating the minimal number of dependencies since I have to do a similar thing for Snap packages. I'll take a look at this (again).

**Comment by fcastilloec** [comment]
@malept that would be great! I haven't had the time to check what is the minimum dependencies for any electron app to work
