### ISSUE TITLE
[Request] Add preinst, postinst, prerm and postrm scripts to the deb file.

### ISSUE THREAD

**Issue by fcastilloec** [unindented/electron-installer-debian#87]
I would like to have the option to pass script files to my deb files.
These are very handy files that are always a good idea to have inside deb files. At the moment there's no way for me to incorporate this files using `electron-installer-debian`

**Comment by jochenkirstaetter** [comment]
Second that.
It would be helpful to have these kind of hooks to further customize the installation handling.

**Comment by fcastilloec** [comment]
PR #91 fix this issue
