### ISSUE TITLE
Building *.deb file problem

### ISSUE THREAD

**Issue by q-bird** [unindented/electron-installer-debian#88]
Hi,

I'm using windows with Visual Studio Code.
I built a simple app with electron + nodejs
I want to build the .deb file so that I can copy to debian machine and install my app.
I followed the instruction in the example folder and it can create `dist/electron-quick-start-linux-ia32`. But 
when it starts to create the package (deb file) it shows the error

I guess the problem is due to your requirements:
```
Requirements

This tool requires fakeroot and dpkg to build the .deb package.

I'd recommend building your packages on your target platform, but if you insist on using Mac OS X, you can install these tools through Homebrew:

$ brew install fakeroot dpkg
```

However, I'm using windows and Visual Studio Code, how can I install the `fakeroot` and `dpkg` ?
Seems that I don't have those tools so it cannnot generate the deb file.

Please help me to resolve this problem!

Thank you,

**Comment by rontran** [comment]
You need to run it in linux.

**Comment by q-bird** [comment]
Hi
I can generate the deb file from linux machine, but I cannot install in my debian device, my device requires "armhf" architecture (not i386 or amd64).

How can I get "armhf"?

I changed `arch i386` from
```
"deb32": "electron-installer-debian --src dist/poopie-linux-ia32/ --arch i386 --config config.json"
```

to `arch armhf` like this:
```
"deb32": "electron-installer-debian --src dist/poopie-linux-ia32/ --arch armhf --config config.json"
```

Then I can install the app on my device, but cannot execute the bin file after installing.
