### ISSUE TITLE
Ubuntu 17.04

### ISSUE THREAD

**Issue by rontran** [unindented/electron-installer-debian#90]
On a virgin Ubuntu 17.04 desktop, after installing my app, doubleclicking on the app icon does nothing.  I then go install visual studio code and it works after that.  So it seems the deb is missing some dependencies for 17.04.

**Comment by fcastilloec** [comment]
If I'm not mistaken, what this means is that your app has visual studio dependencies, not the `electron-installer-debian`. You should use the [options.depends](https://github.com/unindented/electron-installer-debian#optionsdepends-et-al) to add a list of the libraries and packages that your app depends on, so they'll be installed together with your app.
