### ISSUE TITLE
Cannot use user defined icon in dock and start menu

### ISSUE THREAD

**Issue by maplewizard** [unindented/electron-installer-debian#92]
**What version of `electron-installer-debian` are you using?**
0.5.2
**What version of `node` and `npm` are you using?**
node --version
v6.3.1
npm --version
5.4.0
**What operating system are you using?**
deepin linux
**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**
I can compile sucessfully
**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-debian.git
$ cd electron-installer-debian/example
$ DEBUG='electron-installer-debian' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
normally compiled and got file
**What did you expect to happen?**
I expect all the icons are the user defined icon;
**What actually happened?**
the icon on the dock and start menue is electron's default icon;
the icon in /user/share/Applications is user defined icon;
start menu:
![image](https://user-images.githubusercontent.com/1419566/29905831-88daee34-8e43-11e7-8008-f67b42dbe686.png)
dock:
![image](https://user-images.githubusercontent.com/1419566/29905854-9f3c5d52-8e43-11e7-9cc0-b3a37f7b9f3b.png)

**Comment by fcastilloec** [comment]
I think this is a problem with your configuration file not including an icon section. Can you post the contents of the file here? If you didn't use any configuration file, can you post the exact command you use with `electron-installer-debian`?

**Comment by maplewizard** [comment]
the script part of my package.json:
```
"scripts": {
        "start": "electron .",
        "test": "ava",
        "build": "electron-packager . --icon=icons PaperArxiv --platform=linux --arch=x64 --out dist/ --asar --overwrite",
        "deb64": "electron-installer-debian --config deb.json --arch amd64"
    },
```
the deb.json file:
```
{
  "src":  "dist/PaperArxiv-linux-x64",
  "dest": "dist/installers/",
  "icon": "icons/icon.png",
  "categories": [
    "Utility"
  ],
  "lintianOverrides": [
    "changelog-file-missing-in-native-package"
  ]
}
```
I build the package with the following code:
```
npm run build
npm run deb64
```

**Comment by fcastilloec** [comment]
Try removing the `--icon=icons` from your `build` script. This is not necessary for Linux distros, you can read about it [here](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon). Also, you should probably do what the previous link says: 

>icon is set via the [`icon` option in the `BrowserWindow` constructor](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon). 

If this doesn't work, then I'm out of ideas

**Comment by maplewizard** [comment]
Unfortunately, the problem remains

**Comment by fcastilloec** [comment]
I used to have this problem with an app I was helping, as soon as I added the `icon` to my `BrowserWindow` constructor the problem disappeared. But if this didn't work for you, I recommend you extract your `deb` package using `dpkg -x package.deb /path/to/folder` and see if the icon is in the `pixmap` folder and it matches the path inside the `desktop` file.
Nonetheless, this error is not from `electron-installer-debian`

**Comment by maplewizard** [comment]
the content in desktop is:
```
[Desktop Entry]
Name=Paper
Comment=A paper reading tool
GenericName=Paper
Exec=Paper %U
Icon=Paper
Type=Application
StartupNotify=true
Categories=Utility;
```
the file tree is as:
```
├── bin
│   └── Paper -> ../lib/Paper/Paper
├── lib
│   └── Paper
│       ├── blink_image_resources_200_percent.pak
│       ├── content_resources_200_percent.pak
│       ├── content_shell.pak
│       ├── icudtl.dat
│       ├── libffmpeg.so
│       ├── libnode.so
│       ├── LICENSE
│       ├── LICENSES.chromium.html
│       ├── locales
│       │   ├── am.pak
│       │   ├── ar.pak
│       │   ├── bg.pak
│       │   ├── bn.pak
│       │   ├── ca.pak
│       │   ├── cs.pak
│       │   ├── da.pak
│       │   ├── de.pak
│       │   ├── el.pak
│       │   ├── en-GB.pak
│       │   ├── en-US.pak
│       │   ├── es-419.pak
│       │   ├── es.pak
│       │   ├── et.pak
│       │   ├── fake-bidi.pak
│       │   ├── fa.pak
│       │   ├── fil.pak
│       │   ├── fi.pak
│       │   ├── fr.pak
│       │   ├── gu.pak
│       │   ├── he.pak
│       │   ├── hi.pak
│       │   ├── hr.pak
│       │   ├── hu.pak
│       │   ├── id.pak
│       │   ├── it.pak
│       │   ├── ja.pak
│       │   ├── kn.pak
│       │   ├── ko.pak
│       │   ├── lt.pak
│       │   ├── lv.pak
│       │   ├── ml.pak
│       │   ├── mr.pak
│       │   ├── ms.pak
│       │   ├── nb.pak
│       │   ├── nl.pak
│       │   ├── pl.pak
│       │   ├── pt-BR.pak
│       │   ├── pt-PT.pak
│       │   ├── ro.pak
│       │   ├── ru.pak
│       │   ├── sk.pak
│       │   ├── sl.pak
│       │   ├── sr.pak
│       │   ├── sv.pak
│       │   ├── sw.pak
│       │   ├── ta.pak
│       │   ├── te.pak
│       │   ├── th.pak
│       │   ├── tr.pak
│       │   ├── uk.pak
│       │   ├── vi.pak
│       │   ├── zh-CN.pak
│       │   └── zh-TW.pak
│       ├── natives_blob.bin
│       ├── Paper
│       ├── pdf_viewer_resources.pak
│       ├── resources
│       │   ├── app.asar
│       │   └── electron.asar
│       ├── snapshot_blob.bin
│       ├── ui_resources_200_percent.pak
│       ├── version
│       └── views_resources_200_percent.pak
└── share
    ├── applications
    │   └── Paper.desktop
    ├── doc
    │   └── Paper
    │       └── copyright
    ├── lintian
    │   └── overrides
    │       └── Paper
    └── pixmaps
        └── Paper.png
```

**Comment by fcastilloec** [comment]
Yes, everything is as it's supposed to be. Did you check that `share/pixmaps/Paper.png` is the icon you want? Anyway, this issue should be closed because it's not related to `electron-installer-debian`. This program simply copies the icon you specified on the config file into the `usr/share/pixmaps`, the location where the OS looks for icon files

**Comment by maplewizard** [comment]
yes it is. When I double click the file in the bin dir, it runs with my user defined icon. Could you please help to confirm that this is the issue related to the system?

**Comment by fcastilloec** [comment]
Closing issue because https://github.com/unindented/electron-installer-debian/issues/92#issuecomment-326282392 shows that `electron-installer-debian` is working as it should
