### ISSUE TITLE
Handle scalable icons in the configuration

### ISSUE THREAD

**Issue by edhelas** [unindented/electron-installer-debian#94]
```json
{
  "icon": {
    "32x32": "icons/32.png",
    "48x48": "icons/48.png",
    "64x64": "icons/64.png",
    "128x128": "icons/128.png",
    "256x256": "icons/256.png",
    "scalable": "icons/vectorial.svg"
  }
}
```
I have a SVG version of my app icon in the configuration, however electron-installer-debian rename the file to `.png`. Is it possible to keep the file as a SVG in the package ? (it's already in the correct directory).

**Comment by fcastilloec** [comment]
This might be possible to do. I just have to check the debian specifications on how to deal with this

**Comment by fcastilloec** [comment]
Support for this has been added, SVG icons will work only for the `scalable` "resolution", all others will need PNG
