### ISSUE TITLE
Please, build new version of npm package 

### ISSUE THREAD

**Issue by nickmetal** [unindented/electron-installer-debian#97]
npm  4.2.0
node v7.10.1
linux mint 18.1

In package.json i have ```electron-installer-debian": "*"```
And i got ```electron-installer-debian 0.5.2``` after ```npm install```
I look forward to a scripts option (postinst etc) but in 0.5.2 version i did not found this feature.

**Comment by fcastilloec** [comment]
Build v0.6.0 has been released
